var annotated_dup =
[
    [ "Nexus", "namespaceNexus.html", [
      [ "Assets", "namespaceNexus_1_1Assets.html", [
        [ "AssetInfo", "structNexus_1_1Assets_1_1AssetInfo.html", "structNexus_1_1Assets_1_1AssetInfo" ],
        [ "AssetRegistry", "classNexus_1_1Assets_1_1AssetRegistry.html", "classNexus_1_1Assets_1_1AssetRegistry" ]
      ] ],
      [ "D3D12", "namespaceNexus_1_1D3D12.html", [
        [ "AlignedSubObject", "structNexus_1_1D3D12_1_1AlignedSubObject.html", "structNexus_1_1D3D12_1_1AlignedSubObject" ],
        [ "StreamStateBuilder", "classNexus_1_1D3D12_1_1StreamStateBuilder.html", "classNexus_1_1D3D12_1_1StreamStateBuilder" ]
      ] ],
      [ "ECS", "namespaceNexus_1_1ECS.html", [
        [ "ComponentArray", "classNexus_1_1ECS_1_1ComponentArray.html", "classNexus_1_1ECS_1_1ComponentArray" ],
        [ "ComponentPositionData", "structNexus_1_1ECS_1_1ComponentPositionData.html", "structNexus_1_1ECS_1_1ComponentPositionData" ],
        [ "ComponentPtr", "structNexus_1_1ECS_1_1ComponentPtr.html", "structNexus_1_1ECS_1_1ComponentPtr" ],
        [ "ComponentRegistry", "classNexus_1_1ECS_1_1ComponentRegistry.html", "classNexus_1_1ECS_1_1ComponentRegistry" ],
        [ "ComponentStorage", "structNexus_1_1ECS_1_1ComponentStorage.html", "structNexus_1_1ECS_1_1ComponentStorage" ],
        [ "DataTable", "structNexus_1_1ECS_1_1DataTable.html", "structNexus_1_1ECS_1_1DataTable" ],
        [ "IComponentArray", "classNexus_1_1ECS_1_1IComponentArray.html", "classNexus_1_1ECS_1_1IComponentArray" ],
        [ "Registry", "classNexus_1_1ECS_1_1Registry.html", "classNexus_1_1ECS_1_1Registry" ],
        [ "View", "classNexus_1_1ECS_1_1View.html", "classNexus_1_1ECS_1_1View" ]
      ] ],
      [ "GL", "namespaceNexus_1_1GL.html", [
        [ "ContextDescription", "structNexus_1_1GL_1_1ContextDescription.html", "structNexus_1_1GL_1_1ContextDescription" ],
        [ "IGLContext", "classNexus_1_1GL_1_1IGLContext.html", "classNexus_1_1GL_1_1IGLContext" ],
        [ "IOffscreenContext", "classNexus_1_1GL_1_1IOffscreenContext.html", "classNexus_1_1GL_1_1IOffscreenContext" ],
        [ "IViewContext", "classNexus_1_1GL_1_1IViewContext.html", "classNexus_1_1GL_1_1IViewContext" ],
        [ "OffscreenContextWGL", "classNexus_1_1GL_1_1OffscreenContextWGL.html", "classNexus_1_1GL_1_1OffscreenContextWGL" ],
        [ "OpenGLFunctionContext", "classNexus_1_1GL_1_1OpenGLFunctionContext.html", "classNexus_1_1GL_1_1OpenGLFunctionContext" ],
        [ "ViewContextWGL", "classNexus_1_1GL_1_1ViewContextWGL.html", "classNexus_1_1GL_1_1ViewContextWGL" ]
      ] ],
      [ "Graphics", "namespaceNexus_1_1Graphics.html", [
        [ "AccelerationStructureAABBGeometry", "structNexus_1_1Graphics_1_1AccelerationStructureAABBGeometry.html", "structNexus_1_1Graphics_1_1AccelerationStructureAABBGeometry" ],
        [ "AccelerationStructureBuildRange", "structNexus_1_1Graphics_1_1AccelerationStructureBuildRange.html", "structNexus_1_1Graphics_1_1AccelerationStructureBuildRange" ],
        [ "AccelerationStructureBuildSizeDescription", "structNexus_1_1Graphics_1_1AccelerationStructureBuildSizeDescription.html", "structNexus_1_1Graphics_1_1AccelerationStructureBuildSizeDescription" ],
        [ "AccelerationStructureCopyDescription", "structNexus_1_1Graphics_1_1AccelerationStructureCopyDescription.html", "structNexus_1_1Graphics_1_1AccelerationStructureCopyDescription" ],
        [ "AccelerationStructureD3D12", "classNexus_1_1Graphics_1_1AccelerationStructureD3D12.html", "classNexus_1_1Graphics_1_1AccelerationStructureD3D12" ],
        [ "AccelerationStructureDescription", "structNexus_1_1Graphics_1_1AccelerationStructureDescription.html", "structNexus_1_1Graphics_1_1AccelerationStructureDescription" ],
        [ "AccelerationStructureDeviceBufferCopyDescription", "structNexus_1_1Graphics_1_1AccelerationStructureDeviceBufferCopyDescription.html", "structNexus_1_1Graphics_1_1AccelerationStructureDeviceBufferCopyDescription" ],
        [ "AccelerationStructureGeometryBuildDescription", "structNexus_1_1Graphics_1_1AccelerationStructureGeometryBuildDescription.html", "structNexus_1_1Graphics_1_1AccelerationStructureGeometryBuildDescription" ],
        [ "AccelerationStructureGeometryDescription", "structNexus_1_1Graphics_1_1AccelerationStructureGeometryDescription.html", "structNexus_1_1Graphics_1_1AccelerationStructureGeometryDescription" ],
        [ "AccelerationStructureInstance", "structNexus_1_1Graphics_1_1AccelerationStructureInstance.html", "structNexus_1_1Graphics_1_1AccelerationStructureInstance" ],
        [ "AccelerationStructureInstanceGeometry", "structNexus_1_1Graphics_1_1AccelerationStructureInstanceGeometry.html", "structNexus_1_1Graphics_1_1AccelerationStructureInstanceGeometry" ],
        [ "AccelerationStructureProperties", "structNexus_1_1Graphics_1_1AccelerationStructureProperties.html", "structNexus_1_1Graphics_1_1AccelerationStructureProperties" ],
        [ "AccelerationStructureTriangleGeometry", "structNexus_1_1Graphics_1_1AccelerationStructureTriangleGeometry.html", "structNexus_1_1Graphics_1_1AccelerationStructureTriangleGeometry" ],
        [ "AccelerationStructureVk", "classNexus_1_1Graphics_1_1AccelerationStructureVk.html", "classNexus_1_1Graphics_1_1AccelerationStructureVk" ],
        [ "Attribute", "structNexus_1_1Graphics_1_1Attribute.html", "structNexus_1_1Graphics_1_1Attribute" ],
        [ "BatchInfo", "structNexus_1_1Graphics_1_1BatchInfo.html", "structNexus_1_1Graphics_1_1BatchInfo" ],
        [ "BatchRenderer", "classNexus_1_1Graphics_1_1BatchRenderer.html", "classNexus_1_1Graphics_1_1BatchRenderer" ],
        [ "BatchVertex", "structNexus_1_1Graphics_1_1BatchVertex.html", "structNexus_1_1Graphics_1_1BatchVertex" ],
        [ "BeginDebugGroupCommand", "structNexus_1_1Graphics_1_1BeginDebugGroupCommand.html", "structNexus_1_1Graphics_1_1BeginDebugGroupCommand" ],
        [ "BindingInfo", "structNexus_1_1Graphics_1_1BindingInfo.html", "structNexus_1_1Graphics_1_1BindingInfo" ],
        [ "BlendFactorDesc", "structNexus_1_1Graphics_1_1BlendFactorDesc.html", "structNexus_1_1Graphics_1_1BlendFactorDesc" ],
        [ "BlendStateDescription", "structNexus_1_1Graphics_1_1BlendStateDescription.html", "structNexus_1_1Graphics_1_1BlendStateDescription" ],
        [ "BufferBarrierDesc", "structNexus_1_1Graphics_1_1BufferBarrierDesc.html", "structNexus_1_1Graphics_1_1BufferBarrierDesc" ],
        [ "BufferCopy", "structNexus_1_1Graphics_1_1BufferCopy.html", "structNexus_1_1Graphics_1_1BufferCopy" ],
        [ "BufferCopyDescription", "structNexus_1_1Graphics_1_1BufferCopyDescription.html", "structNexus_1_1Graphics_1_1BufferCopyDescription" ],
        [ "BufferRange", "structNexus_1_1Graphics_1_1BufferRange.html", "structNexus_1_1Graphics_1_1BufferRange" ],
        [ "BufferTag", "structNexus_1_1Graphics_1_1BufferTag.html", null ],
        [ "BufferTextureCopyDescription", "structNexus_1_1Graphics_1_1BufferTextureCopyDescription.html", "structNexus_1_1Graphics_1_1BufferTextureCopyDescription" ],
        [ "BuildAccelerationStructuresCommand", "structNexus_1_1Graphics_1_1BuildAccelerationStructuresCommand.html", "structNexus_1_1Graphics_1_1BuildAccelerationStructuresCommand" ],
        [ "CachedShader", "classNexus_1_1Graphics_1_1CachedShader.html", "classNexus_1_1Graphics_1_1CachedShader" ],
        [ "CatmullRom", "classNexus_1_1Graphics_1_1CatmullRom.html", "classNexus_1_1Graphics_1_1CatmullRom" ],
        [ "Character", "structNexus_1_1Graphics_1_1Character.html", "structNexus_1_1Graphics_1_1Character" ],
        [ "CharacterRange", "structNexus_1_1Graphics_1_1CharacterRange.html", "structNexus_1_1Graphics_1_1CharacterRange" ],
        [ "CharacterTextureCoords", "structNexus_1_1Graphics_1_1CharacterTextureCoords.html", "structNexus_1_1Graphics_1_1CharacterTextureCoords" ],
        [ "Circle", "classNexus_1_1Graphics_1_1Circle.html", "classNexus_1_1Graphics_1_1Circle" ],
        [ "ClearColorTargetCommand", "structNexus_1_1Graphics_1_1ClearColorTargetCommand.html", "structNexus_1_1Graphics_1_1ClearColorTargetCommand" ],
        [ "ClearColourValue", "structNexus_1_1Graphics_1_1ClearColourValue.html", "structNexus_1_1Graphics_1_1ClearColourValue" ],
        [ "ClearDepthStencilTargetCommand", "structNexus_1_1Graphics_1_1ClearDepthStencilTargetCommand.html", "structNexus_1_1Graphics_1_1ClearDepthStencilTargetCommand" ],
        [ "ClearDepthStencilValue", "structNexus_1_1Graphics_1_1ClearDepthStencilValue.html", "structNexus_1_1Graphics_1_1ClearDepthStencilValue" ],
        [ "ClearRect", "structNexus_1_1Graphics_1_1ClearRect.html", "structNexus_1_1Graphics_1_1ClearRect" ],
        [ "Colour", "structNexus_1_1Graphics_1_1Colour.html", "structNexus_1_1Graphics_1_1Colour" ],
        [ "CombinedImageSampler", "structNexus_1_1Graphics_1_1CombinedImageSampler.html", "structNexus_1_1Graphics_1_1CombinedImageSampler" ],
        [ "CommandExecutor", "classNexus_1_1Graphics_1_1CommandExecutor.html", "classNexus_1_1Graphics_1_1CommandExecutor" ],
        [ "CommandListDescription", "structNexus_1_1Graphics_1_1CommandListDescription.html", "structNexus_1_1Graphics_1_1CommandListDescription" ],
        [ "CommandQueueD3D12", "classNexus_1_1Graphics_1_1CommandQueueD3D12.html", "classNexus_1_1Graphics_1_1CommandQueueD3D12" ],
        [ "CommandQueueDescription", "structNexus_1_1Graphics_1_1CommandQueueDescription.html", "structNexus_1_1Graphics_1_1CommandQueueDescription" ],
        [ "CommandQueueOpenGL", "classNexus_1_1Graphics_1_1CommandQueueOpenGL.html", "classNexus_1_1Graphics_1_1CommandQueueOpenGL" ],
        [ "CommandQueueVk", "classNexus_1_1Graphics_1_1CommandQueueVk.html", "classNexus_1_1Graphics_1_1CommandQueueVk" ],
        [ "CompilationResult", "structNexus_1_1Graphics_1_1CompilationResult.html", "structNexus_1_1Graphics_1_1CompilationResult" ],
        [ "ComputePipelineDescription", "structNexus_1_1Graphics_1_1ComputePipelineDescription.html", "structNexus_1_1Graphics_1_1ComputePipelineDescription" ],
        [ "CopyBufferToBufferCommand", "structNexus_1_1Graphics_1_1CopyBufferToBufferCommand.html", "structNexus_1_1Graphics_1_1CopyBufferToBufferCommand" ],
        [ "CopyBufferToTextureCommand", "structNexus_1_1Graphics_1_1CopyBufferToTextureCommand.html", "structNexus_1_1Graphics_1_1CopyBufferToTextureCommand" ],
        [ "CopyTextureToBufferCommand", "structNexus_1_1Graphics_1_1CopyTextureToBufferCommand.html", "structNexus_1_1Graphics_1_1CopyTextureToBufferCommand" ],
        [ "CopyTextureToTextureCommand", "structNexus_1_1Graphics_1_1CopyTextureToTextureCommand.html", "structNexus_1_1Graphics_1_1CopyTextureToTextureCommand" ],
        [ "CubemapCameraUniforms", "structNexus_1_1Graphics_1_1CubemapCameraUniforms.html", "structNexus_1_1Graphics_1_1CubemapCameraUniforms" ],
        [ "DepthStencilDescription", "structNexus_1_1Graphics_1_1DepthStencilDescription.html", "structNexus_1_1Graphics_1_1DepthStencilDescription" ],
        [ "DeviceAddressRegion", "structNexus_1_1Graphics_1_1DeviceAddressRegion.html", "structNexus_1_1Graphics_1_1DeviceAddressRegion" ],
        [ "DeviceBufferAccelerationStructureCopyDescription", "structNexus_1_1Graphics_1_1DeviceBufferAccelerationStructureCopyDescription.html", "structNexus_1_1Graphics_1_1DeviceBufferAccelerationStructureCopyDescription" ],
        [ "DeviceBufferDescription", "structNexus_1_1Graphics_1_1DeviceBufferDescription.html", "structNexus_1_1Graphics_1_1DeviceBufferDescription" ],
        [ "DeviceFeatures", "structNexus_1_1Graphics_1_1DeviceFeatures.html", "structNexus_1_1Graphics_1_1DeviceFeatures" ],
        [ "DeviceLimits", "structNexus_1_1Graphics_1_1DeviceLimits.html", "structNexus_1_1Graphics_1_1DeviceLimits" ],
        [ "DispatchDescription", "structNexus_1_1Graphics_1_1DispatchDescription.html", "structNexus_1_1Graphics_1_1DispatchDescription" ],
        [ "DispatchIndirectDescription", "structNexus_1_1Graphics_1_1DispatchIndirectDescription.html", "structNexus_1_1Graphics_1_1DispatchIndirectDescription" ],
        [ "DrawDescription", "structNexus_1_1Graphics_1_1DrawDescription.html", "structNexus_1_1Graphics_1_1DrawDescription" ],
        [ "DrawIndexedDescription", "structNexus_1_1Graphics_1_1DrawIndexedDescription.html", "structNexus_1_1Graphics_1_1DrawIndexedDescription" ],
        [ "DrawIndirectDescription", "structNexus_1_1Graphics_1_1DrawIndirectDescription.html", "structNexus_1_1Graphics_1_1DrawIndirectDescription" ],
        [ "DrawIndirectIndexedDescription", "structNexus_1_1Graphics_1_1DrawIndirectIndexedDescription.html", "structNexus_1_1Graphics_1_1DrawIndirectIndexedDescription" ],
        [ "DrawMeshDescription", "structNexus_1_1Graphics_1_1DrawMeshDescription.html", "structNexus_1_1Graphics_1_1DrawMeshDescription" ],
        [ "DrawMeshIndirectDescription", "structNexus_1_1Graphics_1_1DrawMeshIndirectDescription.html", "structNexus_1_1Graphics_1_1DrawMeshIndirectDescription" ],
        [ "EndDebugGroupCommand", "structNexus_1_1Graphics_1_1EndDebugGroupCommand.html", null ],
        [ "EndRenderingCommand", "structNexus_1_1Graphics_1_1EndRenderingCommand.html", "structNexus_1_1Graphics_1_1EndRenderingCommand" ],
        [ "Extent2D", "structNexus_1_1Graphics_1_1Extent2D.html", "structNexus_1_1Graphics_1_1Extent2D" ],
        [ "FenceD3D12", "classNexus_1_1Graphics_1_1FenceD3D12.html", "classNexus_1_1Graphics_1_1FenceD3D12" ],
        [ "FenceDescription", "structNexus_1_1Graphics_1_1FenceDescription.html", "structNexus_1_1Graphics_1_1FenceDescription" ],
        [ "FenceOpenGL", "classNexus_1_1Graphics_1_1FenceOpenGL.html", "classNexus_1_1Graphics_1_1FenceOpenGL" ],
        [ "FenceVk", "classNexus_1_1Graphics_1_1FenceVk.html", "classNexus_1_1Graphics_1_1FenceVk" ],
        [ "Font", "classNexus_1_1Graphics_1_1Font.html", "classNexus_1_1Graphics_1_1Font" ],
        [ "FontData", "structNexus_1_1Graphics_1_1FontData.html", "structNexus_1_1Graphics_1_1FontData" ],
        [ "FramebufferColourAttachmentDescription", "structNexus_1_1Graphics_1_1FramebufferColourAttachmentDescription.html", "structNexus_1_1Graphics_1_1FramebufferColourAttachmentDescription" ],
        [ "FramebufferTextureCreateDescription", "structNexus_1_1Graphics_1_1FramebufferTextureCreateDescription.html", "structNexus_1_1Graphics_1_1FramebufferTextureCreateDescription" ],
        [ "FramebufferTextureDescription", "structNexus_1_1Graphics_1_1FramebufferTextureDescription.html", "structNexus_1_1Graphics_1_1FramebufferTextureDescription" ],
        [ "FramebufferTextureSetDescription", "structNexus_1_1Graphics_1_1FramebufferTextureSetDescription.html", "structNexus_1_1Graphics_1_1FramebufferTextureSetDescription" ],
        [ "FullscreenQuad", "classNexus_1_1Graphics_1_1FullscreenQuad.html", "classNexus_1_1Graphics_1_1FullscreenQuad" ],
        [ "GraphicsAPICreateInfo", "structNexus_1_1Graphics_1_1GraphicsAPICreateInfo.html", "structNexus_1_1Graphics_1_1GraphicsAPICreateInfo" ],
        [ "GraphicsCapabilities", "structNexus_1_1Graphics_1_1GraphicsCapabilities.html", "structNexus_1_1Graphics_1_1GraphicsCapabilities" ],
        [ "GraphicsPipelineDescription", "structNexus_1_1Graphics_1_1GraphicsPipelineDescription.html", "structNexus_1_1Graphics_1_1GraphicsPipelineDescription" ],
        [ "HandleT", "structNexus_1_1Graphics_1_1HandleT.html", "structNexus_1_1Graphics_1_1HandleT" ],
        [ "HdriProcessor", "classNexus_1_1Graphics_1_1HdriProcessor.html", "classNexus_1_1Graphics_1_1HdriProcessor" ],
        [ "IAccelerationStructure", "classNexus_1_1Graphics_1_1IAccelerationStructure.html", "classNexus_1_1Graphics_1_1IAccelerationStructure" ],
        [ "ICommandList", "classNexus_1_1Graphics_1_1ICommandList.html", "classNexus_1_1Graphics_1_1ICommandList" ],
        [ "ICommandQueue", "classNexus_1_1Graphics_1_1ICommandQueue.html", "classNexus_1_1Graphics_1_1ICommandQueue" ],
        [ "IComputePipeline", "classNexus_1_1Graphics_1_1IComputePipeline.html", "classNexus_1_1Graphics_1_1IComputePipeline" ],
        [ "IDeviceBuffer", "classNexus_1_1Graphics_1_1IDeviceBuffer.html", "classNexus_1_1Graphics_1_1IDeviceBuffer" ],
        [ "IFence", "classNexus_1_1Graphics_1_1IFence.html", "classNexus_1_1Graphics_1_1IFence" ],
        [ "IFramebuffer", "classNexus_1_1Graphics_1_1IFramebuffer.html", "classNexus_1_1Graphics_1_1IFramebuffer" ],
        [ "IGraphicsAPI", "classNexus_1_1Graphics_1_1IGraphicsAPI.html", "classNexus_1_1Graphics_1_1IGraphicsAPI" ],
        [ "IGraphicsDevice", "classNexus_1_1Graphics_1_1IGraphicsDevice.html", "classNexus_1_1Graphics_1_1IGraphicsDevice" ],
        [ "IGraphicsPipeline", "classNexus_1_1Graphics_1_1IGraphicsPipeline.html", "classNexus_1_1Graphics_1_1IGraphicsPipeline" ],
        [ "Image", "structNexus_1_1Graphics_1_1Image.html", "structNexus_1_1Graphics_1_1Image" ],
        [ "IMeshletPipeline", "classNexus_1_1Graphics_1_1IMeshletPipeline.html", "classNexus_1_1Graphics_1_1IMeshletPipeline" ],
        [ "IndexBufferView", "structNexus_1_1Graphics_1_1IndexBufferView.html", "structNexus_1_1Graphics_1_1IndexBufferView" ],
        [ "IndirectDispatchArguments", "structNexus_1_1Graphics_1_1IndirectDispatchArguments.html", "structNexus_1_1Graphics_1_1IndirectDispatchArguments" ],
        [ "IndirectDrawArguments", "structNexus_1_1Graphics_1_1IndirectDrawArguments.html", "structNexus_1_1Graphics_1_1IndirectDrawArguments" ],
        [ "IndirectIndexedDrawArguments", "structNexus_1_1Graphics_1_1IndirectIndexedDrawArguments.html", "structNexus_1_1Graphics_1_1IndirectIndexedDrawArguments" ],
        [ "IndirectMeshArguments", "structNexus_1_1Graphics_1_1IndirectMeshArguments.html", "structNexus_1_1Graphics_1_1IndirectMeshArguments" ],
        [ "IndirectTraceRaysArguments", "structNexus_1_1Graphics_1_1IndirectTraceRaysArguments.html", "structNexus_1_1Graphics_1_1IndirectTraceRaysArguments" ],
        [ "InsertDebugMarkerCommand", "structNexus_1_1Graphics_1_1InsertDebugMarkerCommand.html", "structNexus_1_1Graphics_1_1InsertDebugMarkerCommand" ],
        [ "IPhysicalDevice", "classNexus_1_1Graphics_1_1IPhysicalDevice.html", "classNexus_1_1Graphics_1_1IPhysicalDevice" ],
        [ "IRayTracingPipeline", "classNexus_1_1Graphics_1_1IRayTracingPipeline.html", "classNexus_1_1Graphics_1_1IRayTracingPipeline" ],
        [ "IResourceSet", "classNexus_1_1Graphics_1_1IResourceSet.html", "classNexus_1_1Graphics_1_1IResourceSet" ],
        [ "ISampler", "classNexus_1_1Graphics_1_1ISampler.html", "classNexus_1_1Graphics_1_1ISampler" ],
        [ "IShaderModule", "classNexus_1_1Graphics_1_1IShaderModule.html", "classNexus_1_1Graphics_1_1IShaderModule" ],
        [ "ISurface", "classNexus_1_1Graphics_1_1ISurface.html", "classNexus_1_1Graphics_1_1ISurface" ],
        [ "ISwapchain", "classNexus_1_1Graphics_1_1ISwapchain.html", "classNexus_1_1Graphics_1_1ISwapchain" ],
        [ "ITexelBuffer", "classNexus_1_1Graphics_1_1ITexelBuffer.html", "classNexus_1_1Graphics_1_1ITexelBuffer" ],
        [ "ITexture", "classNexus_1_1Graphics_1_1ITexture.html", "classNexus_1_1Graphics_1_1ITexture" ],
        [ "ITextureView", "classNexus_1_1Graphics_1_1ITextureView.html", "classNexus_1_1Graphics_1_1ITextureView" ],
        [ "ITimingQuery", "classNexus_1_1Graphics_1_1ITimingQuery.html", "classNexus_1_1Graphics_1_1ITimingQuery" ],
        [ "Material", "structNexus_1_1Graphics_1_1Material.html", "structNexus_1_1Graphics_1_1Material" ],
        [ "MemoryBarrierDesc", "structNexus_1_1Graphics_1_1MemoryBarrierDesc.html", "structNexus_1_1Graphics_1_1MemoryBarrierDesc" ],
        [ "Mesh", "classNexus_1_1Graphics_1_1Mesh.html", "classNexus_1_1Graphics_1_1Mesh" ],
        [ "MeshData", "structNexus_1_1Graphics_1_1MeshData.html", "structNexus_1_1Graphics_1_1MeshData" ],
        [ "MeshFactory", "classNexus_1_1Graphics_1_1MeshFactory.html", "classNexus_1_1Graphics_1_1MeshFactory" ],
        [ "MeshletPipelineDescription", "structNexus_1_1Graphics_1_1MeshletPipelineDescription.html", "structNexus_1_1Graphics_1_1MeshletPipelineDescription" ],
        [ "MipmapGenerator", "classNexus_1_1Graphics_1_1MipmapGenerator.html", "classNexus_1_1Graphics_1_1MipmapGenerator" ],
        [ "Model", "classNexus_1_1Graphics_1_1Model.html", "classNexus_1_1Graphics_1_1Model" ],
        [ "ModelCameraUniforms", "structNexus_1_1Graphics_1_1ModelCameraUniforms.html", "structNexus_1_1Graphics_1_1ModelCameraUniforms" ],
        [ "ModelRenderData", "structNexus_1_1Graphics_1_1ModelRenderData.html", "structNexus_1_1Graphics_1_1ModelRenderData" ],
        [ "ModelTransformUniforms", "structNexus_1_1Graphics_1_1ModelTransformUniforms.html", "structNexus_1_1Graphics_1_1ModelTransformUniforms" ],
        [ "Offset3D", "structNexus_1_1Graphics_1_1Offset3D.html", "structNexus_1_1Graphics_1_1Offset3D" ],
        [ "PhysicalDeviceEGL", "classNexus_1_1Graphics_1_1PhysicalDeviceEGL.html", "classNexus_1_1Graphics_1_1PhysicalDeviceEGL" ],
        [ "PhysicalDeviceWGL", "classNexus_1_1Graphics_1_1PhysicalDeviceWGL.html", "classNexus_1_1Graphics_1_1PhysicalDeviceWGL" ],
        [ "Pipeline", "classNexus_1_1Graphics_1_1Pipeline.html", "classNexus_1_1Graphics_1_1Pipeline" ],
        [ "PixelFormatProperties", "structNexus_1_1Graphics_1_1PixelFormatProperties.html", "structNexus_1_1Graphics_1_1PixelFormatProperties" ],
        [ "Polygon", "structNexus_1_1Graphics_1_1Polygon.html", "structNexus_1_1Graphics_1_1Polygon" ],
        [ "PushConstantsDesc", "structNexus_1_1Graphics_1_1PushConstantsDesc.html", "structNexus_1_1Graphics_1_1PushConstantsDesc" ],
        [ "QueueFamilyInfo", "structNexus_1_1Graphics_1_1QueueFamilyInfo.html", "structNexus_1_1Graphics_1_1QueueFamilyInfo" ],
        [ "RasterizerStateDescription", "structNexus_1_1Graphics_1_1RasterizerStateDescription.html", "structNexus_1_1Graphics_1_1RasterizerStateDescription" ],
        [ "RayTracingDeviceDescription", "structNexus_1_1Graphics_1_1RayTracingDeviceDescription.html", "structNexus_1_1Graphics_1_1RayTracingDeviceDescription" ],
        [ "RayTracingPipelineDescription", "structNexus_1_1Graphics_1_1RayTracingPipelineDescription.html", "structNexus_1_1Graphics_1_1RayTracingPipelineDescription" ],
        [ "Rectangle", "structNexus_1_1Graphics_1_1Rectangle.html", "structNexus_1_1Graphics_1_1Rectangle" ],
        [ "ReflectedBufferMember", "structNexus_1_1Graphics_1_1ReflectedBufferMember.html", "structNexus_1_1Graphics_1_1ReflectedBufferMember" ],
        [ "ReflectedResource", "structNexus_1_1Graphics_1_1ReflectedResource.html", "structNexus_1_1Graphics_1_1ReflectedResource" ],
        [ "ReflectedStorageBuffer", "structNexus_1_1Graphics_1_1ReflectedStorageBuffer.html", "structNexus_1_1Graphics_1_1ReflectedStorageBuffer" ],
        [ "ReflectedUniformBuffer", "structNexus_1_1Graphics_1_1ReflectedUniformBuffer.html", "structNexus_1_1Graphics_1_1ReflectedUniformBuffer" ],
        [ "RenderDocAPI", "classNexus_1_1Graphics_1_1RenderDocAPI.html", "classNexus_1_1Graphics_1_1RenderDocAPI" ],
        [ "Renderer3D", "classNexus_1_1Graphics_1_1Renderer3D.html", "classNexus_1_1Graphics_1_1Renderer3D" ],
        [ "ResolveTextureDescription", "structNexus_1_1Graphics_1_1ResolveTextureDescription.html", "structNexus_1_1Graphics_1_1ResolveTextureDescription" ],
        [ "ResourceDescriptor", "structNexus_1_1Graphics_1_1ResourceDescriptor.html", "structNexus_1_1Graphics_1_1ResourceDescriptor" ],
        [ "ResourcePool", "classNexus_1_1Graphics_1_1ResourcePool.html", "classNexus_1_1Graphics_1_1ResourcePool" ],
        [ "ResourceSetBindingDescription", "structNexus_1_1Graphics_1_1ResourceSetBindingDescription.html", "structNexus_1_1Graphics_1_1ResourceSetBindingDescription" ],
        [ "ResourceSetDescription", "structNexus_1_1Graphics_1_1ResourceSetDescription.html", "structNexus_1_1Graphics_1_1ResourceSetDescription" ],
        [ "ResourceSetDescriptors", "structNexus_1_1Graphics_1_1ResourceSetDescriptors.html", "structNexus_1_1Graphics_1_1ResourceSetDescriptors" ],
        [ "ResourceSetTag", "structNexus_1_1Graphics_1_1ResourceSetTag.html", null ],
        [ "RoundedRectangle", "structNexus_1_1Graphics_1_1RoundedRectangle.html", "structNexus_1_1Graphics_1_1RoundedRectangle" ],
        [ "SamplerDescription", "structNexus_1_1Graphics_1_1SamplerDescription.html", "structNexus_1_1Graphics_1_1SamplerDescription" ],
        [ "SamplerTag", "structNexus_1_1Graphics_1_1SamplerTag.html", null ],
        [ "SceneRenderer", "classNexus_1_1Graphics_1_1SceneRenderer.html", "classNexus_1_1Graphics_1_1SceneRenderer" ],
        [ "Scissor", "structNexus_1_1Graphics_1_1Scissor.html", "structNexus_1_1Graphics_1_1Scissor" ],
        [ "ScopedDebugGroup", "classNexus_1_1Graphics_1_1ScopedDebugGroup.html", "classNexus_1_1Graphics_1_1ScopedDebugGroup" ],
        [ "SetBlendFactorCommand", "structNexus_1_1Graphics_1_1SetBlendFactorCommand.html", "structNexus_1_1Graphics_1_1SetBlendFactorCommand" ],
        [ "SetIndexBufferCommand", "structNexus_1_1Graphics_1_1SetIndexBufferCommand.html", "structNexus_1_1Graphics_1_1SetIndexBufferCommand" ],
        [ "SetStencilReferenceCommand", "structNexus_1_1Graphics_1_1SetStencilReferenceCommand.html", "structNexus_1_1Graphics_1_1SetStencilReferenceCommand" ],
        [ "SetVertexBufferCommand", "structNexus_1_1Graphics_1_1SetVertexBufferCommand.html", "structNexus_1_1Graphics_1_1SetVertexBufferCommand" ],
        [ "ShaderAttribute", "structNexus_1_1Graphics_1_1ShaderAttribute.html", "structNexus_1_1Graphics_1_1ShaderAttribute" ],
        [ "ShaderGenerationOptions", "structNexus_1_1Graphics_1_1ShaderGenerationOptions.html", "structNexus_1_1Graphics_1_1ShaderGenerationOptions" ],
        [ "ShaderGenerator", "classNexus_1_1Graphics_1_1ShaderGenerator.html", "classNexus_1_1Graphics_1_1ShaderGenerator" ],
        [ "ShaderGroup", "structNexus_1_1Graphics_1_1ShaderGroup.html", "structNexus_1_1Graphics_1_1ShaderGroup" ],
        [ "ShaderModuleSpecification", "structNexus_1_1Graphics_1_1ShaderModuleSpecification.html", "structNexus_1_1Graphics_1_1ShaderModuleSpecification" ],
        [ "ShaderReflectionData", "structNexus_1_1Graphics_1_1ShaderReflectionData.html", "structNexus_1_1Graphics_1_1ShaderReflectionData" ],
        [ "ShaderResource", "structNexus_1_1Graphics_1_1ShaderResource.html", "structNexus_1_1Graphics_1_1ShaderResource" ],
        [ "ShaderStageFlags", "classNexus_1_1Graphics_1_1ShaderStageFlags.html", "classNexus_1_1Graphics_1_1ShaderStageFlags" ],
        [ "StartTimingQueryCommand", "structNexus_1_1Graphics_1_1StartTimingQueryCommand.html", "structNexus_1_1Graphics_1_1StartTimingQueryCommand" ],
        [ "StencilState", "structNexus_1_1Graphics_1_1StencilState.html", "structNexus_1_1Graphics_1_1StencilState" ],
        [ "StopTimingQueryCommand", "structNexus_1_1Graphics_1_1StopTimingQueryCommand.html", "structNexus_1_1Graphics_1_1StopTimingQueryCommand" ],
        [ "StorageBufferView", "structNexus_1_1Graphics_1_1StorageBufferView.html", "structNexus_1_1Graphics_1_1StorageBufferView" ],
        [ "StorageImageView", "structNexus_1_1Graphics_1_1StorageImageView.html", "structNexus_1_1Graphics_1_1StorageImageView" ],
        [ "StridedDeviceAddressRegion", "structNexus_1_1Graphics_1_1StridedDeviceAddressRegion.html", "structNexus_1_1Graphics_1_1StridedDeviceAddressRegion" ],
        [ "SubresourceFootprint", "structNexus_1_1Graphics_1_1SubresourceFootprint.html", "structNexus_1_1Graphics_1_1SubresourceFootprint" ],
        [ "SubresourceLayers", "structNexus_1_1Graphics_1_1SubresourceLayers.html", "structNexus_1_1Graphics_1_1SubresourceLayers" ],
        [ "SubresourceRange", "structNexus_1_1Graphics_1_1SubresourceRange.html", "structNexus_1_1Graphics_1_1SubresourceRange" ],
        [ "SurfaceD3D12", "classNexus_1_1Graphics_1_1SurfaceD3D12.html", "classNexus_1_1Graphics_1_1SurfaceD3D12" ],
        [ "SurfaceOpenGL", "classNexus_1_1Graphics_1_1SurfaceOpenGL.html", "classNexus_1_1Graphics_1_1SurfaceOpenGL" ],
        [ "SurfaceVk", "classNexus_1_1Graphics_1_1SurfaceVk.html", "classNexus_1_1Graphics_1_1SurfaceVk" ],
        [ "SurfaceWGL", "classNexus_1_1Graphics_1_1SurfaceWGL.html", "classNexus_1_1Graphics_1_1SurfaceWGL" ],
        [ "SurfaceWin32_D3D12", "classNexus_1_1Graphics_1_1SurfaceWin32__D3D12.html", "classNexus_1_1Graphics_1_1SurfaceWin32__D3D12" ],
        [ "SurfaceWin32_Vk", "classNexus_1_1Graphics_1_1SurfaceWin32__Vk.html", "classNexus_1_1Graphics_1_1SurfaceWin32__Vk" ],
        [ "SwapchainDescription", "structNexus_1_1Graphics_1_1SwapchainDescription.html", "structNexus_1_1Graphics_1_1SwapchainDescription" ],
        [ "SwapchainPresentDescription", "structNexus_1_1Graphics_1_1SwapchainPresentDescription.html", "structNexus_1_1Graphics_1_1SwapchainPresentDescription" ],
        [ "TexelBufferD3D12", "classNexus_1_1Graphics_1_1TexelBufferD3D12.html", "classNexus_1_1Graphics_1_1TexelBufferD3D12" ],
        [ "TexelBufferDescription", "structNexus_1_1Graphics_1_1TexelBufferDescription.html", "structNexus_1_1Graphics_1_1TexelBufferDescription" ],
        [ "TexelBufferOpenGL", "classNexus_1_1Graphics_1_1TexelBufferOpenGL.html", "classNexus_1_1Graphics_1_1TexelBufferOpenGL" ],
        [ "TexelBufferVk", "classNexus_1_1Graphics_1_1TexelBufferVk.html", "classNexus_1_1Graphics_1_1TexelBufferVk" ],
        [ "TextureBarrierDesc", "structNexus_1_1Graphics_1_1TextureBarrierDesc.html", "structNexus_1_1Graphics_1_1TextureBarrierDesc" ],
        [ "TextureCopyDescription", "structNexus_1_1Graphics_1_1TextureCopyDescription.html", "structNexus_1_1Graphics_1_1TextureCopyDescription" ],
        [ "TextureDescription", "structNexus_1_1Graphics_1_1TextureDescription.html", "structNexus_1_1Graphics_1_1TextureDescription" ],
        [ "TextureTag", "structNexus_1_1Graphics_1_1TextureTag.html", null ],
        [ "TextureViewD3D12", "classNexus_1_1Graphics_1_1TextureViewD3D12.html", "classNexus_1_1Graphics_1_1TextureViewD3D12" ],
        [ "TextureViewDescription", "structNexus_1_1Graphics_1_1TextureViewDescription.html", "structNexus_1_1Graphics_1_1TextureViewDescription" ],
        [ "TextureViewOpenGL", "classNexus_1_1Graphics_1_1TextureViewOpenGL.html", "classNexus_1_1Graphics_1_1TextureViewOpenGL" ],
        [ "TextureViewVk", "classNexus_1_1Graphics_1_1TextureViewVk.html", "classNexus_1_1Graphics_1_1TextureViewVk" ],
        [ "TraceRaysDescription", "structNexus_1_1Graphics_1_1TraceRaysDescription.html", "structNexus_1_1Graphics_1_1TraceRaysDescription" ],
        [ "TransformMatrix", "structNexus_1_1Graphics_1_1TransformMatrix.html", "structNexus_1_1Graphics_1_1TransformMatrix" ],
        [ "Triangle2D", "structNexus_1_1Graphics_1_1Triangle2D.html", "structNexus_1_1Graphics_1_1Triangle2D" ],
        [ "Triangle3D", "structNexus_1_1Graphics_1_1Triangle3D.html", "structNexus_1_1Graphics_1_1Triangle3D" ],
        [ "UniformBufferView", "structNexus_1_1Graphics_1_1UniformBufferView.html", "structNexus_1_1Graphics_1_1UniformBufferView" ],
        [ "VB_UNIFORM_HDRI_PROCESSOR_CAMERA", "structNexus_1_1Graphics_1_1VB__UNIFORM__HDRI__PROCESSOR__CAMERA.html", "structNexus_1_1Graphics_1_1VB__UNIFORM__HDRI__PROCESSOR__CAMERA" ],
        [ "VertexBufferElement", "structNexus_1_1Graphics_1_1VertexBufferElement.html", "structNexus_1_1Graphics_1_1VertexBufferElement" ],
        [ "VertexBufferLayout", "structNexus_1_1Graphics_1_1VertexBufferLayout.html", "structNexus_1_1Graphics_1_1VertexBufferLayout" ],
        [ "VertexBufferView", "structNexus_1_1Graphics_1_1VertexBufferView.html", "structNexus_1_1Graphics_1_1VertexBufferView" ],
        [ "VertexPosition", "structNexus_1_1Graphics_1_1VertexPosition.html", "structNexus_1_1Graphics_1_1VertexPosition" ],
        [ "VertexPositionTexCoord", "structNexus_1_1Graphics_1_1VertexPositionTexCoord.html", "structNexus_1_1Graphics_1_1VertexPositionTexCoord" ],
        [ "VertexPositionTexCoordColor", "structNexus_1_1Graphics_1_1VertexPositionTexCoordColor.html", "structNexus_1_1Graphics_1_1VertexPositionTexCoordColor" ],
        [ "VertexPositionTexCoordNormal", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormal.html", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormal" ],
        [ "VertexPositionTexCoordNormalColourTangentBitangent", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormalColourTangentBitangent.html", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormalColourTangentBitangent" ],
        [ "VertexPositionTexCoordNormalTangentBitangent", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormalTangentBitangent.html", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormalTangentBitangent" ],
        [ "Viewport", "structNexus_1_1Graphics_1_1Viewport.html", "structNexus_1_1Graphics_1_1Viewport" ],
        [ "WriteMask", "structNexus_1_1Graphics_1_1WriteMask.html", "structNexus_1_1Graphics_1_1WriteMask" ]
      ] ],
      [ "ImGuiUtils", "namespaceNexus_1_1ImGuiUtils.html", [
        [ "ImGuiDescriptorInfo", "structNexus_1_1ImGuiUtils_1_1ImGuiDescriptorInfo.html", "structNexus_1_1ImGuiUtils_1_1ImGuiDescriptorInfo" ],
        [ "ImGuiGraphicsRenderer", "classNexus_1_1ImGuiUtils_1_1ImGuiGraphicsRenderer.html", "classNexus_1_1ImGuiUtils_1_1ImGuiGraphicsRenderer" ],
        [ "ImGuiWindowInfo", "structNexus_1_1ImGuiUtils_1_1ImGuiWindowInfo.html", "structNexus_1_1ImGuiUtils_1_1ImGuiWindowInfo" ]
      ] ],
      [ "OpenGL", "namespaceNexus_1_1OpenGL.html", [
        [ "OpenGLShaderParser", "classNexus_1_1OpenGL_1_1OpenGLShaderParser.html", "classNexus_1_1OpenGL_1_1OpenGLShaderParser" ],
        [ "ReflectedBufferMember", "structNexus_1_1OpenGL_1_1ReflectedBufferMember.html", "structNexus_1_1OpenGL_1_1ReflectedBufferMember" ],
        [ "ReflectedCustomStructs", "structNexus_1_1OpenGL_1_1ReflectedCustomStructs.html", "structNexus_1_1OpenGL_1_1ReflectedCustomStructs" ],
        [ "ReflectedShaderBuffer", "structNexus_1_1OpenGL_1_1ReflectedShaderBuffer.html", "structNexus_1_1OpenGL_1_1ReflectedShaderBuffer" ],
        [ "ReflectedShaderResource", "structNexus_1_1OpenGL_1_1ReflectedShaderResource.html", "structNexus_1_1OpenGL_1_1ReflectedShaderResource" ],
        [ "ReflectedShaderResources", "structNexus_1_1OpenGL_1_1ReflectedShaderResources.html", "structNexus_1_1OpenGL_1_1ReflectedShaderResources" ]
      ] ],
      [ "Processors", "namespaceNexus_1_1Processors.html", [
        [ "AssimpProcessor", "classNexus_1_1Processors_1_1AssimpProcessor.html", "classNexus_1_1Processors_1_1AssimpProcessor" ],
        [ "IProcessor", "classNexus_1_1Processors_1_1IProcessor.html", "classNexus_1_1Processors_1_1IProcessor" ],
        [ "ModelImportData", "structNexus_1_1Processors_1_1ModelImportData.html", "structNexus_1_1Processors_1_1ModelImportData" ],
        [ "ProcessorInfo", "structNexus_1_1Processors_1_1ProcessorInfo.html", "structNexus_1_1Processors_1_1ProcessorInfo" ],
        [ "ProcessorRegistry", "classNexus_1_1Processors_1_1ProcessorRegistry.html", "classNexus_1_1Processors_1_1ProcessorRegistry" ],
        [ "TextureProcessor", "classNexus_1_1Processors_1_1TextureProcessor.html", "classNexus_1_1Processors_1_1TextureProcessor" ]
      ] ],
      [ "Scripting", "namespaceNexus_1_1Scripting.html", [
        [ "NativeScript", "classNexus_1_1Scripting_1_1NativeScript.html", "classNexus_1_1Scripting_1_1NativeScript" ],
        [ "NativeScriptRegistry", "classNexus_1_1Scripting_1_1NativeScriptRegistry.html", "classNexus_1_1Scripting_1_1NativeScriptRegistry" ]
      ] ],
      [ "Utils", "namespaceNexus_1_1Utils.html", [
        [ "ScriptProjectGenerator", "classNexus_1_1Utils_1_1ScriptProjectGenerator.html", "classNexus_1_1Utils_1_1ScriptProjectGenerator" ],
        [ "ShaderSources", "structNexus_1_1Utils_1_1ShaderSources.html", "structNexus_1_1Utils_1_1ShaderSources" ]
      ] ],
      [ "Vk", "namespaceNexus_1_1Vk.html", [
        [ "PNextBuilder", "classNexus_1_1Vk_1_1PNextBuilder.html", "classNexus_1_1Vk_1_1PNextBuilder" ]
      ] ],
      [ "Application", "classNexus_1_1Application.html", "classNexus_1_1Application" ],
      [ "ApplicationDescription", "structNexus_1_1ApplicationDescription.html", "structNexus_1_1ApplicationDescription" ],
      [ "AssetManager", "classNexus_1_1AssetManager.html", "classNexus_1_1AssetManager" ],
      [ "CommandQueueGroup", "structNexus_1_1CommandQueueGroup.html", "structNexus_1_1CommandQueueGroup" ],
      [ "Entity", "structNexus_1_1Entity.html", "structNexus_1_1Entity" ],
      [ "Environment", "structNexus_1_1Environment.html", "structNexus_1_1Environment" ],
      [ "FirstPersonCamera", "classNexus_1_1FirstPersonCamera.html", "classNexus_1_1FirstPersonCamera" ],
      [ "GUID", "structNexus_1_1GUID.html", "structNexus_1_1GUID" ],
      [ "ModelRenderer", "structNexus_1_1ModelRenderer.html", "structNexus_1_1ModelRenderer" ],
      [ "ModelRendererRegister", "structNexus_1_1ModelRendererRegister.html", "structNexus_1_1ModelRendererRegister" ],
      [ "NativeScriptComponent", "structNexus_1_1NativeScriptComponent.html", "structNexus_1_1NativeScriptComponent" ],
      [ "NativeScriptComponentRegister", "structNexus_1_1NativeScriptComponentRegister.html", "structNexus_1_1NativeScriptComponentRegister" ],
      [ "Point2D", "structNexus_1_1Point2D.html", "structNexus_1_1Point2D" ],
      [ "Point3D", "structNexus_1_1Point3D.html", "structNexus_1_1Point3D" ],
      [ "Project", "classNexus_1_1Project.html", "classNexus_1_1Project" ],
      [ "Scene", "structNexus_1_1Scene.html", "structNexus_1_1Scene" ],
      [ "SceneInfo", "structNexus_1_1SceneInfo.html", "structNexus_1_1SceneInfo" ],
      [ "SpriteRendererComponent", "structNexus_1_1SpriteRendererComponent.html", "structNexus_1_1SpriteRendererComponent" ],
      [ "SpriteRendererComponentRegister", "structNexus_1_1SpriteRendererComponentRegister.html", "structNexus_1_1SpriteRendererComponentRegister" ],
      [ "Transform", "structNexus_1_1Transform.html", "structNexus_1_1Transform" ],
      [ "TransformRegister", "structNexus_1_1TransformRegister.html", "structNexus_1_1TransformRegister" ]
    ] ],
    [ "YAML", "namespaceYAML.html", [
      [ "convert< glm::vec2 >", "structYAML_1_1convert_3_01glm_1_1vec2_01_4.html", "structYAML_1_1convert_3_01glm_1_1vec2_01_4" ],
      [ "convert< glm::vec3 >", "structYAML_1_1convert_3_01glm_1_1vec3_01_4.html", "structYAML_1_1convert_3_01glm_1_1vec3_01_4" ],
      [ "convert< glm::vec4 >", "structYAML_1_1convert_3_01glm_1_1vec4_01_4.html", "structYAML_1_1convert_3_01glm_1_1vec4_01_4" ],
      [ "convert< Nexus::ModelRenderer >", "structYAML_1_1convert_3_01Nexus_1_1ModelRenderer_01_4.html", "structYAML_1_1convert_3_01Nexus_1_1ModelRenderer_01_4" ],
      [ "convert< Nexus::NativeScriptComponent >", "structYAML_1_1convert_3_01Nexus_1_1NativeScriptComponent_01_4.html", "structYAML_1_1convert_3_01Nexus_1_1NativeScriptComponent_01_4" ],
      [ "convert< Nexus::SceneInfo >", "structYAML_1_1convert_3_01Nexus_1_1SceneInfo_01_4.html", "structYAML_1_1convert_3_01Nexus_1_1SceneInfo_01_4" ],
      [ "convert< Nexus::SpriteRendererComponent >", "structYAML_1_1convert_3_01Nexus_1_1SpriteRendererComponent_01_4.html", "structYAML_1_1convert_3_01Nexus_1_1SpriteRendererComponent_01_4" ],
      [ "convert< Nexus::Transform >", "structYAML_1_1convert_3_01Nexus_1_1Transform_01_4.html", "structYAML_1_1convert_3_01Nexus_1_1Transform_01_4" ]
    ] ],
    [ "AllocationTracker", "structAllocationTracker.html", "structAllocationTracker" ],
    [ "AutoHandle", "classAutoHandle.html", "classAutoHandle" ]
];