var hierarchy =
[
    [ "Nexus::Graphics::AccelerationStructureAABBGeometry", "structNexus_1_1Graphics_1_1AccelerationStructureAABBGeometry.html", null ],
    [ "Nexus::Graphics::AccelerationStructureBuildRange", "structNexus_1_1Graphics_1_1AccelerationStructureBuildRange.html", null ],
    [ "Nexus::Graphics::AccelerationStructureBuildSizeDescription", "structNexus_1_1Graphics_1_1AccelerationStructureBuildSizeDescription.html", null ],
    [ "Nexus::Graphics::AccelerationStructureCopyDescription", "structNexus_1_1Graphics_1_1AccelerationStructureCopyDescription.html", null ],
    [ "Nexus::Graphics::AccelerationStructureDescription", "structNexus_1_1Graphics_1_1AccelerationStructureDescription.html", null ],
    [ "Nexus::Graphics::AccelerationStructureDeviceBufferCopyDescription", "structNexus_1_1Graphics_1_1AccelerationStructureDeviceBufferCopyDescription.html", null ],
    [ "Nexus::Graphics::AccelerationStructureGeometryBuildDescription", "structNexus_1_1Graphics_1_1AccelerationStructureGeometryBuildDescription.html", null ],
    [ "Nexus::Graphics::AccelerationStructureGeometryDescription", "structNexus_1_1Graphics_1_1AccelerationStructureGeometryDescription.html", null ],
    [ "Nexus::Graphics::AccelerationStructureInstance", "structNexus_1_1Graphics_1_1AccelerationStructureInstance.html", null ],
    [ "Nexus::Graphics::AccelerationStructureInstanceGeometry", "structNexus_1_1Graphics_1_1AccelerationStructureInstanceGeometry.html", null ],
    [ "Nexus::Graphics::AccelerationStructureProperties", "structNexus_1_1Graphics_1_1AccelerationStructureProperties.html", null ],
    [ "Nexus::Graphics::AccelerationStructureTriangleGeometry", "structNexus_1_1Graphics_1_1AccelerationStructureTriangleGeometry.html", null ],
    [ "Nexus::D3D12::AlignedSubObject< T >", "structNexus_1_1D3D12_1_1AlignedSubObject.html", null ],
    [ "AllocationTracker", "structAllocationTracker.html", null ],
    [ "Nexus::Application", "classNexus_1_1Application.html", null ],
    [ "Nexus::ApplicationDescription", "structNexus_1_1ApplicationDescription.html", null ],
    [ "Nexus::Assets::AssetInfo", "structNexus_1_1Assets_1_1AssetInfo.html", null ],
    [ "Nexus::AssetManager", "classNexus_1_1AssetManager.html", null ],
    [ "Nexus::Assets::AssetRegistry", "classNexus_1_1Assets_1_1AssetRegistry.html", null ],
    [ "Nexus::Graphics::Attribute", "structNexus_1_1Graphics_1_1Attribute.html", null ],
    [ "AutoHandle< HandleType >", "classAutoHandle.html", null ],
    [ "Nexus::Graphics::BatchInfo", "structNexus_1_1Graphics_1_1BatchInfo.html", null ],
    [ "Nexus::Graphics::BatchRenderer", "classNexus_1_1Graphics_1_1BatchRenderer.html", null ],
    [ "Nexus::Graphics::BatchVertex", "structNexus_1_1Graphics_1_1BatchVertex.html", null ],
    [ "Nexus::Graphics::BeginDebugGroupCommand", "structNexus_1_1Graphics_1_1BeginDebugGroupCommand.html", null ],
    [ "Nexus::Graphics::BindingInfo", "structNexus_1_1Graphics_1_1BindingInfo.html", null ],
    [ "Nexus::Graphics::BlendFactorDesc", "structNexus_1_1Graphics_1_1BlendFactorDesc.html", null ],
    [ "Nexus::Graphics::BlendStateDescription", "structNexus_1_1Graphics_1_1BlendStateDescription.html", null ],
    [ "Nexus::Graphics::BufferBarrierDesc", "structNexus_1_1Graphics_1_1BufferBarrierDesc.html", null ],
    [ "Nexus::Graphics::BufferCopy", "structNexus_1_1Graphics_1_1BufferCopy.html", null ],
    [ "Nexus::Graphics::BufferCopyDescription", "structNexus_1_1Graphics_1_1BufferCopyDescription.html", null ],
    [ "Nexus::Graphics::BufferRange", "structNexus_1_1Graphics_1_1BufferRange.html", null ],
    [ "Nexus::Graphics::BufferTag", "structNexus_1_1Graphics_1_1BufferTag.html", null ],
    [ "Nexus::Graphics::BufferTextureCopyDescription", "structNexus_1_1Graphics_1_1BufferTextureCopyDescription.html", null ],
    [ "Nexus::Graphics::BuildAccelerationStructuresCommand", "structNexus_1_1Graphics_1_1BuildAccelerationStructuresCommand.html", null ],
    [ "Nexus::Graphics::CachedShader", "classNexus_1_1Graphics_1_1CachedShader.html", null ],
    [ "Nexus::Graphics::CatmullRom< T >", "classNexus_1_1Graphics_1_1CatmullRom.html", null ],
    [ "Nexus::Graphics::Character", "structNexus_1_1Graphics_1_1Character.html", null ],
    [ "Nexus::Graphics::CharacterRange", "structNexus_1_1Graphics_1_1CharacterRange.html", null ],
    [ "Nexus::Graphics::CharacterTextureCoords", "structNexus_1_1Graphics_1_1CharacterTextureCoords.html", null ],
    [ "Nexus::Graphics::Circle< T >", "classNexus_1_1Graphics_1_1Circle.html", null ],
    [ "Nexus::Graphics::ClearColorTargetCommand", "structNexus_1_1Graphics_1_1ClearColorTargetCommand.html", null ],
    [ "Nexus::Graphics::ClearColourValue", "structNexus_1_1Graphics_1_1ClearColourValue.html", null ],
    [ "Nexus::Graphics::ClearDepthStencilTargetCommand", "structNexus_1_1Graphics_1_1ClearDepthStencilTargetCommand.html", null ],
    [ "Nexus::Graphics::ClearDepthStencilValue", "structNexus_1_1Graphics_1_1ClearDepthStencilValue.html", null ],
    [ "Nexus::Graphics::ClearRect", "structNexus_1_1Graphics_1_1ClearRect.html", null ],
    [ "Nexus::Graphics::Colour", "structNexus_1_1Graphics_1_1Colour.html", null ],
    [ "Nexus::Graphics::CombinedImageSampler", "structNexus_1_1Graphics_1_1CombinedImageSampler.html", null ],
    [ "Nexus::Graphics::CommandExecutor", "classNexus_1_1Graphics_1_1CommandExecutor.html", null ],
    [ "Nexus::Graphics::CommandListDescription", "structNexus_1_1Graphics_1_1CommandListDescription.html", null ],
    [ "Nexus::Graphics::CommandQueueDescription", "structNexus_1_1Graphics_1_1CommandQueueDescription.html", null ],
    [ "Nexus::CommandQueueGroup", "structNexus_1_1CommandQueueGroup.html", null ],
    [ "Nexus::Graphics::CompilationResult", "structNexus_1_1Graphics_1_1CompilationResult.html", null ],
    [ "Nexus::ECS::ComponentPositionData", "structNexus_1_1ECS_1_1ComponentPositionData.html", null ],
    [ "Nexus::ECS::ComponentPtr", "structNexus_1_1ECS_1_1ComponentPtr.html", null ],
    [ "Nexus::ECS::ComponentRegistry", "classNexus_1_1ECS_1_1ComponentRegistry.html", null ],
    [ "Nexus::ECS::ComponentStorage", "structNexus_1_1ECS_1_1ComponentStorage.html", null ],
    [ "Nexus::Graphics::ComputePipelineDescription", "structNexus_1_1Graphics_1_1ComputePipelineDescription.html", null ],
    [ "Nexus::GL::ContextDescription", "structNexus_1_1GL_1_1ContextDescription.html", null ],
    [ "YAML::convert< glm::vec2 >", "structYAML_1_1convert_3_01glm_1_1vec2_01_4.html", null ],
    [ "YAML::convert< glm::vec3 >", "structYAML_1_1convert_3_01glm_1_1vec3_01_4.html", null ],
    [ "YAML::convert< glm::vec4 >", "structYAML_1_1convert_3_01glm_1_1vec4_01_4.html", null ],
    [ "YAML::convert< Nexus::ModelRenderer >", "structYAML_1_1convert_3_01Nexus_1_1ModelRenderer_01_4.html", null ],
    [ "YAML::convert< Nexus::NativeScriptComponent >", "structYAML_1_1convert_3_01Nexus_1_1NativeScriptComponent_01_4.html", null ],
    [ "YAML::convert< Nexus::SceneInfo >", "structYAML_1_1convert_3_01Nexus_1_1SceneInfo_01_4.html", null ],
    [ "YAML::convert< Nexus::SpriteRendererComponent >", "structYAML_1_1convert_3_01Nexus_1_1SpriteRendererComponent_01_4.html", null ],
    [ "YAML::convert< Nexus::Transform >", "structYAML_1_1convert_3_01Nexus_1_1Transform_01_4.html", null ],
    [ "Nexus::Graphics::CopyBufferToBufferCommand", "structNexus_1_1Graphics_1_1CopyBufferToBufferCommand.html", null ],
    [ "Nexus::Graphics::CopyBufferToTextureCommand", "structNexus_1_1Graphics_1_1CopyBufferToTextureCommand.html", null ],
    [ "Nexus::Graphics::CopyTextureToBufferCommand", "structNexus_1_1Graphics_1_1CopyTextureToBufferCommand.html", null ],
    [ "Nexus::Graphics::CopyTextureToTextureCommand", "structNexus_1_1Graphics_1_1CopyTextureToTextureCommand.html", null ],
    [ "Nexus::Graphics::CubemapCameraUniforms", "structNexus_1_1Graphics_1_1CubemapCameraUniforms.html", null ],
    [ "Nexus::ECS::DataTable< T >", "structNexus_1_1ECS_1_1DataTable.html", null ],
    [ "Nexus::Graphics::DepthStencilDescription", "structNexus_1_1Graphics_1_1DepthStencilDescription.html", null ],
    [ "Nexus::Graphics::DeviceAddressRegion", "structNexus_1_1Graphics_1_1DeviceAddressRegion.html", null ],
    [ "Nexus::Graphics::DeviceBufferAccelerationStructureCopyDescription", "structNexus_1_1Graphics_1_1DeviceBufferAccelerationStructureCopyDescription.html", null ],
    [ "Nexus::Graphics::DeviceBufferDescription", "structNexus_1_1Graphics_1_1DeviceBufferDescription.html", null ],
    [ "Nexus::Graphics::DeviceFeatures", "structNexus_1_1Graphics_1_1DeviceFeatures.html", null ],
    [ "Nexus::Graphics::DeviceLimits", "structNexus_1_1Graphics_1_1DeviceLimits.html", null ],
    [ "Nexus::Graphics::DispatchDescription", "structNexus_1_1Graphics_1_1DispatchDescription.html", null ],
    [ "Nexus::Graphics::DispatchIndirectDescription", "structNexus_1_1Graphics_1_1DispatchIndirectDescription.html", null ],
    [ "Nexus::Graphics::DrawDescription", "structNexus_1_1Graphics_1_1DrawDescription.html", null ],
    [ "Nexus::Graphics::DrawIndexedDescription", "structNexus_1_1Graphics_1_1DrawIndexedDescription.html", null ],
    [ "Nexus::Graphics::DrawIndirectDescription", "structNexus_1_1Graphics_1_1DrawIndirectDescription.html", null ],
    [ "Nexus::Graphics::DrawIndirectIndexedDescription", "structNexus_1_1Graphics_1_1DrawIndirectIndexedDescription.html", null ],
    [ "Nexus::Graphics::DrawMeshDescription", "structNexus_1_1Graphics_1_1DrawMeshDescription.html", null ],
    [ "Nexus::Graphics::DrawMeshIndirectDescription", "structNexus_1_1Graphics_1_1DrawMeshIndirectDescription.html", null ],
    [ "Nexus::Graphics::EndDebugGroupCommand", "structNexus_1_1Graphics_1_1EndDebugGroupCommand.html", null ],
    [ "Nexus::Graphics::EndRenderingCommand", "structNexus_1_1Graphics_1_1EndRenderingCommand.html", null ],
    [ "Nexus::Entity", "structNexus_1_1Entity.html", null ],
    [ "Nexus::Graphics::ResourcePool< T, Handle >::Entry", "structNexus_1_1Graphics_1_1ResourcePool_1_1Entry.html", null ],
    [ "Nexus::Environment", "structNexus_1_1Environment.html", null ],
    [ "Nexus::Graphics::Extent2D", "structNexus_1_1Graphics_1_1Extent2D.html", null ],
    [ "Nexus::Graphics::FenceDescription", "structNexus_1_1Graphics_1_1FenceDescription.html", null ],
    [ "Nexus::FirstPersonCamera", "classNexus_1_1FirstPersonCamera.html", null ],
    [ "Nexus::Graphics::Font", "classNexus_1_1Graphics_1_1Font.html", null ],
    [ "Nexus::Graphics::FontData", "structNexus_1_1Graphics_1_1FontData.html", null ],
    [ "Nexus::Graphics::FramebufferColourAttachmentDescription", "structNexus_1_1Graphics_1_1FramebufferColourAttachmentDescription.html", null ],
    [ "Nexus::Graphics::FramebufferTextureCreateDescription", "structNexus_1_1Graphics_1_1FramebufferTextureCreateDescription.html", null ],
    [ "Nexus::Graphics::FramebufferTextureDescription", "structNexus_1_1Graphics_1_1FramebufferTextureDescription.html", null ],
    [ "Nexus::Graphics::FramebufferTextureSetDescription", "structNexus_1_1Graphics_1_1FramebufferTextureSetDescription.html", null ],
    [ "Nexus::Graphics::FullscreenQuad", "classNexus_1_1Graphics_1_1FullscreenQuad.html", null ],
    [ "Nexus::Graphics::GraphicsAPICreateInfo", "structNexus_1_1Graphics_1_1GraphicsAPICreateInfo.html", null ],
    [ "Nexus::Graphics::GraphicsCapabilities", "structNexus_1_1Graphics_1_1GraphicsCapabilities.html", null ],
    [ "Nexus::Graphics::GraphicsPipelineDescription", "structNexus_1_1Graphics_1_1GraphicsPipelineDescription.html", null ],
    [ "Nexus::GUID", "structNexus_1_1GUID.html", null ],
    [ "Nexus::Graphics::HandleT< Tag >", "structNexus_1_1Graphics_1_1HandleT.html", null ],
    [ "Nexus::Graphics::HdriProcessor", "classNexus_1_1Graphics_1_1HdriProcessor.html", null ],
    [ "Nexus::Graphics::IAccelerationStructure", "classNexus_1_1Graphics_1_1IAccelerationStructure.html", [
      [ "Nexus::Graphics::AccelerationStructureD3D12", "classNexus_1_1Graphics_1_1AccelerationStructureD3D12.html", null ],
      [ "Nexus::Graphics::AccelerationStructureVk", "classNexus_1_1Graphics_1_1AccelerationStructureVk.html", null ]
    ] ],
    [ "Nexus::Graphics::ICommandList", "classNexus_1_1Graphics_1_1ICommandList.html", null ],
    [ "Nexus::Graphics::ICommandQueue", "classNexus_1_1Graphics_1_1ICommandQueue.html", [
      [ "Nexus::Graphics::CommandQueueD3D12", "classNexus_1_1Graphics_1_1CommandQueueD3D12.html", null ],
      [ "Nexus::Graphics::CommandQueueOpenGL", "classNexus_1_1Graphics_1_1CommandQueueOpenGL.html", null ],
      [ "Nexus::Graphics::CommandQueueVk", "classNexus_1_1Graphics_1_1CommandQueueVk.html", null ]
    ] ],
    [ "Nexus::ECS::IComponentArray", "classNexus_1_1ECS_1_1IComponentArray.html", [
      [ "Nexus::ECS::ComponentArray< T >", "classNexus_1_1ECS_1_1ComponentArray.html", null ]
    ] ],
    [ "Nexus::Graphics::IDeviceBuffer", "classNexus_1_1Graphics_1_1IDeviceBuffer.html", null ],
    [ "Nexus::Graphics::IFence", "classNexus_1_1Graphics_1_1IFence.html", [
      [ "Nexus::Graphics::FenceD3D12", "classNexus_1_1Graphics_1_1FenceD3D12.html", null ],
      [ "Nexus::Graphics::FenceOpenGL", "classNexus_1_1Graphics_1_1FenceOpenGL.html", null ],
      [ "Nexus::Graphics::FenceVk", "classNexus_1_1Graphics_1_1FenceVk.html", null ]
    ] ],
    [ "Nexus::Graphics::IFramebuffer", "classNexus_1_1Graphics_1_1IFramebuffer.html", null ],
    [ "Nexus::GL::IGLContext", "classNexus_1_1GL_1_1IGLContext.html", [
      [ "Nexus::GL::IOffscreenContext", "classNexus_1_1GL_1_1IOffscreenContext.html", [
        [ "Nexus::GL::OffscreenContextWGL", "classNexus_1_1GL_1_1OffscreenContextWGL.html", null ]
      ] ],
      [ "Nexus::GL::IViewContext", "classNexus_1_1GL_1_1IViewContext.html", [
        [ "Nexus::GL::ViewContextWGL", "classNexus_1_1GL_1_1ViewContextWGL.html", null ]
      ] ]
    ] ],
    [ "Nexus::Graphics::IGraphicsAPI", "classNexus_1_1Graphics_1_1IGraphicsAPI.html", null ],
    [ "Nexus::Graphics::IGraphicsDevice", "classNexus_1_1Graphics_1_1IGraphicsDevice.html", null ],
    [ "Nexus::Graphics::Image", "structNexus_1_1Graphics_1_1Image.html", null ],
    [ "Nexus::ImGuiUtils::ImGuiDescriptorInfo", "structNexus_1_1ImGuiUtils_1_1ImGuiDescriptorInfo.html", null ],
    [ "Nexus::ImGuiUtils::ImGuiGraphicsRenderer", "classNexus_1_1ImGuiUtils_1_1ImGuiGraphicsRenderer.html", null ],
    [ "Nexus::ImGuiUtils::ImGuiWindowInfo", "structNexus_1_1ImGuiUtils_1_1ImGuiWindowInfo.html", null ],
    [ "Nexus::Graphics::IndexBufferView", "structNexus_1_1Graphics_1_1IndexBufferView.html", null ],
    [ "Nexus::Graphics::IndirectDispatchArguments", "structNexus_1_1Graphics_1_1IndirectDispatchArguments.html", null ],
    [ "Nexus::Graphics::IndirectDrawArguments", "structNexus_1_1Graphics_1_1IndirectDrawArguments.html", null ],
    [ "Nexus::Graphics::IndirectIndexedDrawArguments", "structNexus_1_1Graphics_1_1IndirectIndexedDrawArguments.html", null ],
    [ "Nexus::Graphics::IndirectMeshArguments", "structNexus_1_1Graphics_1_1IndirectMeshArguments.html", null ],
    [ "Nexus::Graphics::IndirectTraceRaysArguments", "structNexus_1_1Graphics_1_1IndirectTraceRaysArguments.html", null ],
    [ "Nexus::Graphics::InsertDebugMarkerCommand", "structNexus_1_1Graphics_1_1InsertDebugMarkerCommand.html", null ],
    [ "Nexus::Graphics::IPhysicalDevice", "classNexus_1_1Graphics_1_1IPhysicalDevice.html", null ],
    [ "Nexus::Processors::IProcessor", "classNexus_1_1Processors_1_1IProcessor.html", [
      [ "Nexus::Processors::AssimpProcessor", "classNexus_1_1Processors_1_1AssimpProcessor.html", null ],
      [ "Nexus::Processors::TextureProcessor", "classNexus_1_1Processors_1_1TextureProcessor.html", null ]
    ] ],
    [ "Nexus::Graphics::IResourceSet", "classNexus_1_1Graphics_1_1IResourceSet.html", null ],
    [ "Nexus::Graphics::ISampler", "classNexus_1_1Graphics_1_1ISampler.html", null ],
    [ "Nexus::Graphics::IShaderModule", "classNexus_1_1Graphics_1_1IShaderModule.html", null ],
    [ "Nexus::Graphics::ISurface", "classNexus_1_1Graphics_1_1ISurface.html", [
      [ "Nexus::Graphics::SurfaceD3D12", "classNexus_1_1Graphics_1_1SurfaceD3D12.html", [
        [ "Nexus::Graphics::SurfaceWin32_D3D12", "classNexus_1_1Graphics_1_1SurfaceWin32__D3D12.html", null ]
      ] ],
      [ "Nexus::Graphics::SurfaceOpenGL", "classNexus_1_1Graphics_1_1SurfaceOpenGL.html", [
        [ "Nexus::Graphics::SurfaceWGL", "classNexus_1_1Graphics_1_1SurfaceWGL.html", null ]
      ] ],
      [ "Nexus::Graphics::SurfaceVk", "classNexus_1_1Graphics_1_1SurfaceVk.html", [
        [ "Nexus::Graphics::SurfaceWin32_Vk", "classNexus_1_1Graphics_1_1SurfaceWin32__Vk.html", null ]
      ] ]
    ] ],
    [ "Nexus::Graphics::ISwapchain", "classNexus_1_1Graphics_1_1ISwapchain.html", null ],
    [ "Nexus::ECS::View< Args >::iterator", "classNexus_1_1ECS_1_1View_1_1iterator.html", null ],
    [ "Nexus::Graphics::ITexelBuffer", "classNexus_1_1Graphics_1_1ITexelBuffer.html", [
      [ "Nexus::Graphics::TexelBufferD3D12", "classNexus_1_1Graphics_1_1TexelBufferD3D12.html", null ],
      [ "Nexus::Graphics::TexelBufferOpenGL", "classNexus_1_1Graphics_1_1TexelBufferOpenGL.html", null ],
      [ "Nexus::Graphics::TexelBufferVk", "classNexus_1_1Graphics_1_1TexelBufferVk.html", null ]
    ] ],
    [ "Nexus::Graphics::ITexture", "classNexus_1_1Graphics_1_1ITexture.html", null ],
    [ "Nexus::Graphics::ITextureView", "classNexus_1_1Graphics_1_1ITextureView.html", [
      [ "Nexus::Graphics::TextureViewD3D12", "classNexus_1_1Graphics_1_1TextureViewD3D12.html", null ],
      [ "Nexus::Graphics::TextureViewOpenGL", "classNexus_1_1Graphics_1_1TextureViewOpenGL.html", null ],
      [ "Nexus::Graphics::TextureViewVk", "classNexus_1_1Graphics_1_1TextureViewVk.html", null ]
    ] ],
    [ "Nexus::Graphics::ITimingQuery", "classNexus_1_1Graphics_1_1ITimingQuery.html", null ],
    [ "Nexus::Graphics::Material", "structNexus_1_1Graphics_1_1Material.html", null ],
    [ "Nexus::Graphics::MemoryBarrierDesc", "structNexus_1_1Graphics_1_1MemoryBarrierDesc.html", null ],
    [ "Nexus::Graphics::Mesh", "classNexus_1_1Graphics_1_1Mesh.html", null ],
    [ "Nexus::Graphics::MeshData", "structNexus_1_1Graphics_1_1MeshData.html", null ],
    [ "Nexus::Graphics::MeshFactory", "classNexus_1_1Graphics_1_1MeshFactory.html", null ],
    [ "Nexus::Graphics::MeshletPipelineDescription", "structNexus_1_1Graphics_1_1MeshletPipelineDescription.html", null ],
    [ "Nexus::Graphics::MipmapGenerator", "classNexus_1_1Graphics_1_1MipmapGenerator.html", null ],
    [ "Nexus::Graphics::Model", "classNexus_1_1Graphics_1_1Model.html", null ],
    [ "Nexus::Graphics::ModelCameraUniforms", "structNexus_1_1Graphics_1_1ModelCameraUniforms.html", null ],
    [ "Nexus::Processors::ModelImportData", "structNexus_1_1Processors_1_1ModelImportData.html", null ],
    [ "Nexus::Graphics::ModelRenderData", "structNexus_1_1Graphics_1_1ModelRenderData.html", null ],
    [ "Nexus::ModelRenderer", "structNexus_1_1ModelRenderer.html", null ],
    [ "Nexus::ModelRendererRegister", "structNexus_1_1ModelRendererRegister.html", null ],
    [ "Nexus::Graphics::ModelTransformUniforms", "structNexus_1_1Graphics_1_1ModelTransformUniforms.html", null ],
    [ "Nexus::Scripting::NativeScript", "classNexus_1_1Scripting_1_1NativeScript.html", null ],
    [ "Nexus::NativeScriptComponent", "structNexus_1_1NativeScriptComponent.html", null ],
    [ "Nexus::NativeScriptComponentRegister", "structNexus_1_1NativeScriptComponentRegister.html", null ],
    [ "Nexus::Scripting::NativeScriptRegistry", "classNexus_1_1Scripting_1_1NativeScriptRegistry.html", null ],
    [ "Nexus::Graphics::Offset3D", "structNexus_1_1Graphics_1_1Offset3D.html", null ],
    [ "Nexus::GL::OpenGLFunctionContext", "classNexus_1_1GL_1_1OpenGLFunctionContext.html", null ],
    [ "Nexus::OpenGL::OpenGLShaderParser", "classNexus_1_1OpenGL_1_1OpenGLShaderParser.html", null ],
    [ "PhysicalDeviceOpenGL", null, [
      [ "Nexus::Graphics::PhysicalDeviceEGL", "classNexus_1_1Graphics_1_1PhysicalDeviceEGL.html", null ],
      [ "Nexus::Graphics::PhysicalDeviceWGL", "classNexus_1_1Graphics_1_1PhysicalDeviceWGL.html", null ]
    ] ],
    [ "Nexus::Graphics::Pipeline", "classNexus_1_1Graphics_1_1Pipeline.html", [
      [ "Nexus::Graphics::IComputePipeline", "classNexus_1_1Graphics_1_1IComputePipeline.html", null ],
      [ "Nexus::Graphics::IGraphicsPipeline", "classNexus_1_1Graphics_1_1IGraphicsPipeline.html", null ],
      [ "Nexus::Graphics::IMeshletPipeline", "classNexus_1_1Graphics_1_1IMeshletPipeline.html", null ],
      [ "Nexus::Graphics::IRayTracingPipeline", "classNexus_1_1Graphics_1_1IRayTracingPipeline.html", null ]
    ] ],
    [ "Nexus::Graphics::PixelFormatProperties", "structNexus_1_1Graphics_1_1PixelFormatProperties.html", null ],
    [ "Nexus::Vk::PNextBuilder", "classNexus_1_1Vk_1_1PNextBuilder.html", null ],
    [ "Nexus::Point2D< T >", "structNexus_1_1Point2D.html", null ],
    [ "Nexus::Point2D< float >", "structNexus_1_1Point2D.html", null ],
    [ "Nexus::Point2D< uint32_t >", "structNexus_1_1Point2D.html", null ],
    [ "Nexus::Point3D< T >", "structNexus_1_1Point3D.html", null ],
    [ "Nexus::Graphics::Polygon", "structNexus_1_1Graphics_1_1Polygon.html", null ],
    [ "Nexus::Processors::ProcessorInfo", "structNexus_1_1Processors_1_1ProcessorInfo.html", null ],
    [ "Nexus::Processors::ProcessorRegistry", "classNexus_1_1Processors_1_1ProcessorRegistry.html", null ],
    [ "Nexus::Project", "classNexus_1_1Project.html", null ],
    [ "Nexus::Graphics::PushConstantsDesc", "structNexus_1_1Graphics_1_1PushConstantsDesc.html", null ],
    [ "Nexus::Graphics::QueueFamilyInfo", "structNexus_1_1Graphics_1_1QueueFamilyInfo.html", null ],
    [ "Nexus::Graphics::RasterizerStateDescription", "structNexus_1_1Graphics_1_1RasterizerStateDescription.html", null ],
    [ "Nexus::Graphics::RayTracingDeviceDescription", "structNexus_1_1Graphics_1_1RayTracingDeviceDescription.html", null ],
    [ "Nexus::Graphics::RayTracingPipelineDescription", "structNexus_1_1Graphics_1_1RayTracingPipelineDescription.html", null ],
    [ "Nexus::Graphics::Rectangle< T >", "structNexus_1_1Graphics_1_1Rectangle.html", null ],
    [ "Nexus::Graphics::ReflectedBufferMember", "structNexus_1_1Graphics_1_1ReflectedBufferMember.html", null ],
    [ "Nexus::OpenGL::ReflectedBufferMember", "structNexus_1_1OpenGL_1_1ReflectedBufferMember.html", null ],
    [ "Nexus::OpenGL::ReflectedCustomStructs", "structNexus_1_1OpenGL_1_1ReflectedCustomStructs.html", null ],
    [ "Nexus::Graphics::ReflectedResource", "structNexus_1_1Graphics_1_1ReflectedResource.html", null ],
    [ "Nexus::OpenGL::ReflectedShaderBuffer", "structNexus_1_1OpenGL_1_1ReflectedShaderBuffer.html", null ],
    [ "Nexus::OpenGL::ReflectedShaderResource", "structNexus_1_1OpenGL_1_1ReflectedShaderResource.html", null ],
    [ "Nexus::OpenGL::ReflectedShaderResources", "structNexus_1_1OpenGL_1_1ReflectedShaderResources.html", null ],
    [ "Nexus::Graphics::ReflectedStorageBuffer", "structNexus_1_1Graphics_1_1ReflectedStorageBuffer.html", null ],
    [ "Nexus::Graphics::ReflectedUniformBuffer", "structNexus_1_1Graphics_1_1ReflectedUniformBuffer.html", null ],
    [ "Nexus::ECS::Registry", "classNexus_1_1ECS_1_1Registry.html", null ],
    [ "Nexus::Graphics::RenderDocAPI", "classNexus_1_1Graphics_1_1RenderDocAPI.html", null ],
    [ "Nexus::Graphics::Renderer3D", "classNexus_1_1Graphics_1_1Renderer3D.html", null ],
    [ "Nexus::Graphics::ResolveTextureDescription", "structNexus_1_1Graphics_1_1ResolveTextureDescription.html", null ],
    [ "Nexus::Graphics::ResourceDescriptor", "structNexus_1_1Graphics_1_1ResourceDescriptor.html", null ],
    [ "Nexus::Graphics::ResourcePool< T, Handle >", "classNexus_1_1Graphics_1_1ResourcePool.html", null ],
    [ "Nexus::Graphics::ResourceSetBindingDescription", "structNexus_1_1Graphics_1_1ResourceSetBindingDescription.html", null ],
    [ "Nexus::Graphics::ResourceSetDescription", "structNexus_1_1Graphics_1_1ResourceSetDescription.html", null ],
    [ "Nexus::Graphics::ResourceSetDescriptors", "structNexus_1_1Graphics_1_1ResourceSetDescriptors.html", null ],
    [ "Nexus::Graphics::ResourceSetTag", "structNexus_1_1Graphics_1_1ResourceSetTag.html", null ],
    [ "Nexus::Graphics::RoundedRectangle", "structNexus_1_1Graphics_1_1RoundedRectangle.html", null ],
    [ "Nexus::Graphics::SamplerDescription", "structNexus_1_1Graphics_1_1SamplerDescription.html", null ],
    [ "Nexus::Graphics::SamplerTag", "structNexus_1_1Graphics_1_1SamplerTag.html", null ],
    [ "Nexus::Scene", "structNexus_1_1Scene.html", null ],
    [ "Nexus::SceneInfo", "structNexus_1_1SceneInfo.html", null ],
    [ "Nexus::Graphics::SceneRenderer", "classNexus_1_1Graphics_1_1SceneRenderer.html", null ],
    [ "Nexus::Graphics::Scissor", "structNexus_1_1Graphics_1_1Scissor.html", null ],
    [ "Nexus::Graphics::ScopedDebugGroup", "classNexus_1_1Graphics_1_1ScopedDebugGroup.html", null ],
    [ "Nexus::Utils::ScriptProjectGenerator", "classNexus_1_1Utils_1_1ScriptProjectGenerator.html", null ],
    [ "Nexus::Graphics::SetBlendFactorCommand", "structNexus_1_1Graphics_1_1SetBlendFactorCommand.html", null ],
    [ "Nexus::Graphics::SetIndexBufferCommand", "structNexus_1_1Graphics_1_1SetIndexBufferCommand.html", null ],
    [ "Nexus::Graphics::SetStencilReferenceCommand", "structNexus_1_1Graphics_1_1SetStencilReferenceCommand.html", null ],
    [ "Nexus::Graphics::SetVertexBufferCommand", "structNexus_1_1Graphics_1_1SetVertexBufferCommand.html", null ],
    [ "Nexus::Graphics::ShaderAttribute", "structNexus_1_1Graphics_1_1ShaderAttribute.html", null ],
    [ "Nexus::Graphics::ShaderGenerationOptions", "structNexus_1_1Graphics_1_1ShaderGenerationOptions.html", null ],
    [ "Nexus::Graphics::ShaderGenerator", "classNexus_1_1Graphics_1_1ShaderGenerator.html", null ],
    [ "Nexus::Graphics::ShaderGroup", "structNexus_1_1Graphics_1_1ShaderGroup.html", null ],
    [ "Nexus::Graphics::ShaderModuleSpecification", "structNexus_1_1Graphics_1_1ShaderModuleSpecification.html", null ],
    [ "Nexus::Graphics::ShaderReflectionData", "structNexus_1_1Graphics_1_1ShaderReflectionData.html", null ],
    [ "Nexus::Graphics::ShaderResource", "structNexus_1_1Graphics_1_1ShaderResource.html", null ],
    [ "Nexus::Utils::ShaderSources", "structNexus_1_1Utils_1_1ShaderSources.html", null ],
    [ "Nexus::Graphics::ShaderStageFlags", "classNexus_1_1Graphics_1_1ShaderStageFlags.html", null ],
    [ "Nexus::SpriteRendererComponent", "structNexus_1_1SpriteRendererComponent.html", null ],
    [ "Nexus::SpriteRendererComponentRegister", "structNexus_1_1SpriteRendererComponentRegister.html", null ],
    [ "Nexus::Graphics::StartTimingQueryCommand", "structNexus_1_1Graphics_1_1StartTimingQueryCommand.html", null ],
    [ "Nexus::Graphics::StencilState", "structNexus_1_1Graphics_1_1StencilState.html", null ],
    [ "Nexus::Graphics::StopTimingQueryCommand", "structNexus_1_1Graphics_1_1StopTimingQueryCommand.html", null ],
    [ "Nexus::Graphics::StorageBufferView", "structNexus_1_1Graphics_1_1StorageBufferView.html", null ],
    [ "Nexus::Graphics::StorageImageView", "structNexus_1_1Graphics_1_1StorageImageView.html", null ],
    [ "Nexus::D3D12::StreamStateBuilder", "classNexus_1_1D3D12_1_1StreamStateBuilder.html", null ],
    [ "Nexus::Graphics::StridedDeviceAddressRegion", "structNexus_1_1Graphics_1_1StridedDeviceAddressRegion.html", null ],
    [ "Nexus::Graphics::SubresourceFootprint", "structNexus_1_1Graphics_1_1SubresourceFootprint.html", null ],
    [ "Nexus::Graphics::SubresourceLayers", "structNexus_1_1Graphics_1_1SubresourceLayers.html", null ],
    [ "Nexus::Graphics::SubresourceRange", "structNexus_1_1Graphics_1_1SubresourceRange.html", null ],
    [ "Nexus::Graphics::SwapchainDescription", "structNexus_1_1Graphics_1_1SwapchainDescription.html", null ],
    [ "Nexus::Graphics::SwapchainPresentDescription", "structNexus_1_1Graphics_1_1SwapchainPresentDescription.html", null ],
    [ "Nexus::Graphics::TexelBufferDescription", "structNexus_1_1Graphics_1_1TexelBufferDescription.html", null ],
    [ "Nexus::Graphics::TextureBarrierDesc", "structNexus_1_1Graphics_1_1TextureBarrierDesc.html", null ],
    [ "Nexus::Graphics::TextureCopyDescription", "structNexus_1_1Graphics_1_1TextureCopyDescription.html", null ],
    [ "Nexus::Graphics::TextureDescription", "structNexus_1_1Graphics_1_1TextureDescription.html", null ],
    [ "Nexus::Graphics::TextureTag", "structNexus_1_1Graphics_1_1TextureTag.html", null ],
    [ "Nexus::Graphics::TextureViewDescription", "structNexus_1_1Graphics_1_1TextureViewDescription.html", null ],
    [ "Nexus::Graphics::TraceRaysDescription", "structNexus_1_1Graphics_1_1TraceRaysDescription.html", null ],
    [ "Nexus::Transform", "structNexus_1_1Transform.html", null ],
    [ "Nexus::Graphics::TransformMatrix", "structNexus_1_1Graphics_1_1TransformMatrix.html", null ],
    [ "Nexus::TransformRegister", "structNexus_1_1TransformRegister.html", null ],
    [ "Nexus::Graphics::Triangle2D", "structNexus_1_1Graphics_1_1Triangle2D.html", null ],
    [ "Nexus::Graphics::Triangle3D", "structNexus_1_1Graphics_1_1Triangle3D.html", null ],
    [ "Nexus::Graphics::UniformBufferView", "structNexus_1_1Graphics_1_1UniformBufferView.html", null ],
    [ "Nexus::Graphics::VB_UNIFORM_HDRI_PROCESSOR_CAMERA", "structNexus_1_1Graphics_1_1VB__UNIFORM__HDRI__PROCESSOR__CAMERA.html", null ],
    [ "Nexus::Graphics::VertexBufferElement", "structNexus_1_1Graphics_1_1VertexBufferElement.html", null ],
    [ "Nexus::Graphics::VertexBufferLayout", "structNexus_1_1Graphics_1_1VertexBufferLayout.html", null ],
    [ "Nexus::Graphics::VertexBufferView", "structNexus_1_1Graphics_1_1VertexBufferView.html", null ],
    [ "Nexus::Graphics::VertexPosition", "structNexus_1_1Graphics_1_1VertexPosition.html", null ],
    [ "Nexus::Graphics::VertexPositionTexCoord", "structNexus_1_1Graphics_1_1VertexPositionTexCoord.html", null ],
    [ "Nexus::Graphics::VertexPositionTexCoordColor", "structNexus_1_1Graphics_1_1VertexPositionTexCoordColor.html", null ],
    [ "Nexus::Graphics::VertexPositionTexCoordNormal", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormal.html", null ],
    [ "Nexus::Graphics::VertexPositionTexCoordNormalColourTangentBitangent", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormalColourTangentBitangent.html", null ],
    [ "Nexus::Graphics::VertexPositionTexCoordNormalTangentBitangent", "structNexus_1_1Graphics_1_1VertexPositionTexCoordNormalTangentBitangent.html", null ],
    [ "Nexus::ECS::View< Args >", "classNexus_1_1ECS_1_1View.html", null ],
    [ "Nexus::Graphics::Viewport", "structNexus_1_1Graphics_1_1Viewport.html", null ],
    [ "Nexus::Graphics::WriteMask", "structNexus_1_1Graphics_1_1WriteMask.html", null ]
];