set(CPM_DOWNLOAD_VERSION 0.42.3)

if(NOT CPM_SOURCE_CACHE)
  set(CPM_SOURCE_CACHE "${CMAKE_SOURCE_DIR}/.cache")
endif()

set(CPM_DOWNLOAD_LOCATION "${CPM_SOURCE_CACHE}/CPM_${CPM_DOWNLOAD_VERSION}.cmake")

if(NOT EXISTS ${CPM_DOWNLOAD_LOCATION})
  message(STATUS "Downloading CPM.cmake")
  file(DOWNLOAD
    "https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake"
    ${CPM_DOWNLOAD_LOCATION}
  )
endif()

include(${CPM_DOWNLOAD_LOCATION})

# ============================================================
#  ABI‑safe cache key
# ============================================================
function(nx_compute_cache_key out_var name version)
    set(_cc_id    "${CMAKE_CXX_COMPILER_ID}")
    set(_cc_ver   "${CMAKE_CXX_COMPILER_VERSION}")
    set(_sys_name "${CMAKE_SYSTEM_NAME}")
    set(_sys_proc "${CMAKE_SYSTEM_PROCESSOR}")

    if(CMAKE_CONFIGURATION_TYPES)
        set(_cfg "$<CONFIG>")
    else()
        set(_cfg "${CMAKE_BUILD_TYPE}")
    endif()

    set(_std "${CMAKE_CXX_STANDARD}")

    set(_key
        "${name}-${version}"
        "${_sys_name}-${_sys_proc}"
        "${_cc_id}-${_cc_ver}"
        "cxx${_std}"
        "${_cfg}"
    )

    string(REPLACE ";" "_" _key "${_key}")
    set(${out_var} "${_key}" PARENT_SCOPE)
endfunction()


include(FetchContent)

# ============================================================
# FetchContentWithBinaryCache
# ============================================================
function(FetchContentWithBinaryCache)
    set(options)
    set(oneValueArgs NAME VERSION GIT_REPOSITORY GIT_TAG)
    set(multiValueArgs OPTIONS)
    cmake_parse_arguments(FCBC "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(POLICY CMP0169)
        cmake_policy(SET CMP0169 OLD)
    endif()

    if(NOT FCBC_NAME)
        message(FATAL_ERROR "FetchContentWithBinaryCache: NAME is required")
    endif()

    if(NOT FCBC_VERSION)
        set(FCBC_VERSION "${FCBC_GIT_TAG}")
    endif()

    nx_compute_cache_key(PKG_KEY "${FCBC_NAME}" "${FCBC_VERSION}")

    set(CACHE_ROOT "${CMAKE_SOURCE_DIR}/fc-binary-cache")
    set(PKG_ROOT   "${CACHE_ROOT}/${PKG_KEY}")
    set(PKG_INSTALL_PREFIX "${PKG_ROOT}/install")
    set(PKG_IMPORT_FILE    "${PKG_ROOT}/nx-import.cmake")
    set(PKG_COMPLETE_FILE  "${PKG_INSTALL_PREFIX}/.complete")

    # ============================================================
    # 1. Cached path — import and return
    # ============================================================
    if(EXISTS "${PKG_COMPLETE_FILE}" AND EXISTS "${PKG_IMPORT_FILE}")
        message(STATUS "[FCBC] Using cached binary for ${FCBC_NAME} (${PKG_KEY})")
        include("${PKG_IMPORT_FILE}")
        return()
    endif()

    # ============================================================
    # 2. Fetch with FetchContent
    # ============================================================
    message(STATUS "[FCBC] No cache for ${FCBC_NAME} (${PKG_KEY}), fetching with FetchContent")

    FetchContent_Declare(
        ${FCBC_NAME}
        GIT_REPOSITORY ${FCBC_GIT_REPOSITORY}
        GIT_TAG        ${FCBC_GIT_TAG}
    )

    FetchContent_MakeAvailable(${FCBC_NAME})

    set(DEP_SOURCE_DIR "${${FCBC_NAME}_SOURCE_DIR}")

    # ============================================================
    # 3. Create a dedicated build directory for installation
    # ============================================================
    set(DEP_INSTALL_BUILD "${PKG_ROOT}/build")
    file(MAKE_DIRECTORY "${DEP_INSTALL_BUILD}")
    file(MAKE_DIRECTORY "${PKG_INSTALL_PREFIX}")

    # ============================================================
    # 4. Configure + build + install
    # ============================================================
    add_custom_target(${FCBC_NAME}_install ALL
        COMMAND "${CMAKE_COMMAND}"
            -S "${DEP_SOURCE_DIR}"
            -B "${DEP_INSTALL_BUILD}"
            -DCMAKE_INSTALL_PREFIX=${PKG_INSTALL_PREFIX}
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON
            ${FCBC_OPTIONS}

        COMMAND "${CMAKE_COMMAND}" --build "${DEP_INSTALL_BUILD}"
            $<$<BOOL:${CMAKE_CONFIGURATION_TYPES}>:--config $<CONFIG>>

        COMMAND "${CMAKE_COMMAND}" --install "${DEP_INSTALL_BUILD}"
            $<$<BOOL:${CMAKE_CONFIGURATION_TYPES}>:--config $<CONFIG>>

        COMMAND "${CMAKE_COMMAND}" -E touch "${PKG_COMPLETE_FILE}"

        COMMENT "Building and installing ${FCBC_NAME} into ${PKG_INSTALL_PREFIX}"
    )

    # ============================================================
    # 5. Generate import file
    # ============================================================
    set(_pkg_cmake_dir "${PKG_INSTALL_PREFIX}/lib/cmake/${FCBC_NAME}")

    file(WRITE "${PKG_IMPORT_FILE}" "
# Auto-generated by FetchContentWithBinaryCache
set(${FCBC_NAME}_DIR \"${_pkg_cmake_dir}\")
find_package(${FCBC_NAME} CONFIG REQUIRED)
")
endfunction()
